name: Go
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      NGROK_TEST_ONLINE: 1
      NGROK_TEST_LONG: 1
      NGROK_TEST_FLAKEY: 1
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
    - uses: HatsuneMiku3939/direnv-action@v1
    - name: direnv allow
      run: direnv allow .
    - name: Build
      run: direnv exec . go build -v ./...
    - name: Build Examples
      run: direnv exec . go build -v ./examples/...
    - name: Test
      run: direnv exec . go test -v ./...
